<a href="https://colab.research.google.com/github/Andro2k/Metodos-Numericos/blob/main/Tarea_11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <a href="https://colab.research.google.com/drive/1oy3dutQQNsXZFcQYGzgSyO_Y5dU94Fa6?usp=sharing">**Tarea 11**</a>
* **Estudiante:** Jose Luis Andino
* **Materia:** Metodos Numericos
* **Carrera:** Computación
* **Docente:** Jonathan A. Zea

* **Github** https://github.com/Andro2k/Metodos-Numericos/blob/main/Tarea_11.ipynb

## **CONJUNTO DE EJERCICIOS**



### **Ejercicio 1.**
Encuentre las primeras dos iteraciones del método de Jacobi para los siguientes sistemas lineales, por medio de $x^{(0)} = 0:$

**A)**
> $
3x_1 - x_2 + x_3 = 1\\
3x_1 + 6x_2 + 2x_3 = 0\\
3x_1 + 3x_2 + 7x_3 = 4
$

**B)**
> $
10x_1 - x_2 = 9\\
-x_1 + 10x_2 - 2x_3 = 7\\
-2x_2 + 10x_3 = 6
$

**C)**
> $
10x_1 - 5x_2 = 6\\
5x_1 + 10x_2 - 4x_3 = 25\\
- 4x_2 + 8x_3 - x_4= -11\\
-x_3 + 5x_4= -11
$

**D)**
> $
4x_1 + x_2 + x_3 + x_5= 6\\
-x_1 - 3x_2 + x_3 + x_4 = 6\\
2x_1 + x_2 + 5x_3 - x_4 - x_5= 6\\
-x_1 - x_2 - x_3 + 4x_4 = 6\\
2x_2 - x_3 + x_4 + 4x_5 = 6
$

In [45]:
import numpy as np

def jacobi(A, b, x0, num_iterations):
    n = len(A)
    x = x0.copy()
    x_new = np.zeros_like(x0)

    for iteration in range(num_iterations):
        for i in range(n):
            sum1 = np.dot(A[i, :i], x[:i])
            sum2 = np.dot(A[i, i+1:], x[i+1:])
            x_new[i] = (b[i] - sum1 - sum2) / A[i, i]
        x = x_new.copy()

    return x

# Sistema A
A_A = np.array([
    [3, -1, 1],
    [3, 6, 2],
    [3, 3, 7]
])
b_A = np.array([1, 0, 4])
x0_A = np.zeros(3)
iterations_A = jacobi(A_A, b_A, x0_A, 2)
print("Sistema A: Primeras dos iteraciones")
print("Iteración 1:", iterations_A)

# Sistema B
A_B = np.array([
    [10, -1, 0],
    [-1, 10, -2],
    [0, -2, 10]
])
b_B = np.array([9, 7, 6])
x0_B = np.zeros(3)
iterations_B = jacobi(A_B, b_B, x0_B, 2)
print("\nSistema B: Primeras dos iteraciones")
print("Iteración 1:", iterations_B)

# Sistema C
A_C = np.array([
    [10, -5, 0, 0],
    [5, 10, -4, 0],
    [0, -4, 8, -1],
    [0, 0, -1, 5]
])
b_C = np.array([6, 25, -11, -11])
x0_C = np.zeros(4)
iterations_C = jacobi(A_C, b_C, x0_C, 2)
print("\nSistema C: Primeras dos iteraciones")
print("Iteración 1:", iterations_C)

# Sistema D
A_D = np.array([
    [4, 1, 1, 0, 1],
    [-1, -3, 1, 1, 0],
    [2, 1, 5, -1, -1],
    [-1, -1, -1, 4, 0],
    [0, 2, -1, 1, 4]
])
b_D = np.array([6, 6, 6, 6, 6])
x0_D = np.zeros(5)
iterations_D = jacobi(A_D, b_D, x0_D, 2)
print("\nSistema D: Primeras dos iteraciones")
print("Iteración 1:", iterations_D)


Sistema A: Primeras dos iteraciones
Iteración 1: [ 0.14285714 -0.35714286  0.42857143]

Sistema B: Primeras dos iteraciones
Iteración 1: [0.97 0.91 0.74]

Sistema C: Primeras dos iteraciones
Iteración 1: [ 1.85   1.65  -0.4   -2.475]

Sistema D: Primeras dos iteraciones
Iteración 1: [ 1.325 -1.6    1.6    1.675  2.425]


### **Ejercicio 2.**
Repita el ejercicio 1 usando el método de Gauss-Seidel.


In [46]:
import numpy as np

def gauss_seidel(A, b, x0, num_iterations):
    n = len(A)
    x = x0.copy()

    for iteration in range(num_iterations):
        for i in range(n):
            sum1 = np.dot(A[i, :i], x[:i])
            sum2 = np.dot(A[i, i+1:], x[i+1:])
            x[i] = (b[i] - sum1 - sum2) / A[i, i]

    return x

# Sistema A
A_A = np.array([
    [3, -1, 1],
    [3, 6, 2],
    [3, 3, 7]
])
b_A = np.array([1, 0, 4])
x0_A = np.zeros(3)
iterations_A = gauss_seidel(A_A, b_A, x0_A, 2)
print("Sistema A: Primeras dos iteraciones")
print("Iteración 1:", iterations_A)

# Sistema B
A_B = np.array([
    [10, -1, 0],
    [-1, 10, -2],
    [0, -2, 10]
])
b_B = np.array([9, 7, 6])
x0_B = np.zeros(3)
iterations_B = gauss_seidel(A_B, b_B, x0_B, 2)
print("\nSistema B: Primeras dos iteraciones")
print("Iteración 1:", iterations_B)

# Sistema C
A_C = np.array([
    [10, -5, 0, 0],
    [5, 10, -4, 0],
    [0, -4, 8, -1],
    [0, 0, -1, 5]
])
b_C = np.array([6, 25, -11, -11])
x0_C = np.zeros(4)
iterations_C = gauss_seidel(A_C, b_C, x0_C, 2)
print("\nSistema C: Primeras dos iteraciones")
print("Iteración 1:", iterations_C)

# Sistema D
A_D = np.array([
    [4, 1, 1, 0, 1],
    [-1, -3, 1, 1, 0],
    [2, 1, 5, -1, -1],
    [-1, -1, -1, 4, 0],
    [0, 2, -1, 1, 4]
])
b_D = np.array([6, 6, 6, 6, 6])
x0_D = np.zeros(5)
iterations_D = gauss_seidel(A_D, b_D, x0_D, 2)
print("\nSistema D: Primeras dos iteraciones")
print("Iteración 1:", iterations_D)


Sistema A: Primeras dos iteraciones
Iteración 1: [ 0.11111111 -0.22222222  0.61904762]

Sistema B: Primeras dos iteraciones
Iteración 1: [0.979  0.9495 0.7899]

Sistema C: Primeras dos iteraciones
Iteración 1: [ 1.7       1.54     -0.886875 -2.377375]

Sistema D: Primeras dos iteraciones
Iteración 1: [ 1.1890625  -1.52135417  1.86239583  1.88252604  2.25564453]


### **Ejercicio 3.**
Utilice el método de Jacobi para resolver los sistemas lineales en el ejercicio $1$, con $\text{TOL} = 10^{-3}$.

In [47]:
import numpy as np

def jacobi_with_tolerance(A, b, x0, tol):
    n = len(A)
    x = x0.copy()
    x_new = np.zeros_like(x0)
    iteration = 0

    while True:
        iteration += 1
        for i in range(n):
            sum1 = np.dot(A[i, :i], x[:i])
            sum2 = np.dot(A[i, i+1:], x[i+1:])
            x_new[i] = (b[i] - sum1 - sum2) / A[i, i]

        # Check convergence
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            break

        x = x_new.copy()

    return x, iteration

# Definir sistemas
systems = [
    (np.array([
        [3, -1, 1],
        [3, 6, 2],
        [3, 3, 7]
    ]), np.array([1, 0, 4]), np.zeros(3)),

    (np.array([
        [10, -1, 0],
        [-1, 10, -2],
        [0, -2, 10]
    ]), np.array([9, 7, 6]), np.zeros(3)),

    (np.array([
        [10, -5, 0, 0],
        [5, 10, -4, 0],
        [0, -4, 8, -1],
        [0, 0, -1, 5]
    ]), np.array([6, 25, -11, -11]), np.zeros(4)),

    (np.array([
        [4, 1, 1, 0, 1],
        [-1, -3, 1, 1, 0],
        [2, 1, 5, -1, -1],
        [-1, -1, -1, 4, 0],
        [0, 2, -1, 1, 4]
    ]), np.array([6, 6, 6, 6, 6]), np.zeros(5))
]

tol = 1e-3

for i, (A, b, x0) in enumerate(systems, start=1):
    solution, num_iterations = jacobi_with_tolerance(A, b, x0, tol)
    print(f"Sistema {chr(64 + i)}: Solución después de {num_iterations} iteraciones")
    print(solution)
    print()


Sistema A: Solución después de 9 iteraciones
[ 0.03502399 -0.23732106  0.65737656]

Sistema B: Solución después de 6 iteraciones
[0.99555 0.95725 0.7911 ]

Sistema C: Solución después de 9 iteraciones
[ 1.32860625  1.45754297 -0.94492344 -2.38882617]

Sistema D: Solución después de 12 iteraciones
[ 0.78729533 -1.00286688  1.86536849  1.91281957  1.98914507]



### **Ejercicio 4.**
Utilice el método de Gauss-Seidel para resolver los sistemas lineales en el ejercicio $1$, con $\text{TOL} = 10^{-3}$.

In [48]:
import numpy as np

def gauss_seidel_with_tolerance(A, b, x0, tol):
    n = len(A)
    x = x0.copy()
    iteration = 0

    while True:
        iteration += 1
        x_old = x.copy()

        for i in range(n):
            sum1 = np.dot(A[i, :i], x[:i])
            sum2 = np.dot(A[i, i+1:], x_old[i+1:])
            x[i] = (b[i] - sum1 - sum2) / A[i, i]

        # Check convergence
        if np.linalg.norm(x - x_old, ord=np.inf) < tol:
            break

    return x, iteration

# Definir sistemas
systems = [
    (np.array([
        [3, -1, 1],
        [3, 6, 2],
        [3, 3, 7]
    ]), np.array([1, 0, 4]), np.zeros(3)),

    (np.array([
        [10, -1, 0],
        [-1, 10, -2],
        [0, -2, 10]
    ]), np.array([9, 7, 6]), np.zeros(3)),

    (np.array([
        [10, -5, 0, 0],
        [5, 10, -4, 0],
        [0, -4, 8, -1],
        [0, 0, -1, 5]
    ]), np.array([6, 25, -11, -11]), np.zeros(4)),

    (np.array([
        [4, 1, 1, 0, 1],
        [-1, -3, 1, 1, 0],
        [2, 1, 5, -1, -1],
        [-1, -1, -1, 4, 0],
        [0, 2, -1, 1, 4]
    ]), np.array([6, 6, 6, 6, 6]), np.zeros(5))
]

tol = 1e-3

for i, (A, b, x0) in enumerate(systems, start=1):
    solution, num_iterations = gauss_seidel_with_tolerance(A, b, x0, tol)
    print(f"Sistema {chr(64 + i)}: Solución después de {num_iterations} iteraciones")
    print(solution)
    print()


Sistema A: Solución después de 6 iteraciones
[ 0.03535107 -0.23678863  0.65775895]

Sistema B: Solución después de 4 iteraciones
[0.9957475  0.95787375 0.79157475]

Sistema C: Solución después de 6 iteraciones
[ 1.3288368   1.4576714  -0.94478369 -2.38895674]

Sistema D: Solución después de 7 iteraciones
[ 0.78668253 -1.00271872  1.86628339  1.9125618   1.98978976]



### **Ejercicio 5.**
El sistema lineal

>$
2x_1 - x_2 + x_3 = -1\\
2x_1 + 2x_2 + 2x_3 = 4\\
-x_1 - x_2 + 2x_3 = -5
$

tiene la solución $(1, 2, -1)$.

- **a**) Muestre que el método de Jacobi con $\mathbf{x}^{(0)} = 0$ falla al proporcionar una buena aproximación después de 25 iteraciones.

- **b**) Utilice el método de Gauss-Seidel con $\mathbf{x}^{(0)} = 0$ para aproximar la solución para el sistema lineal dentro de $10^{-5}$.

In [49]:
import numpy as np

def jacobi(A, b, x0, max_iterations):
    n = len(A)
    x = x0.copy()
    x_new = np.zeros_like(x0)
    for iteration in range(max_iterations):
        for i in range(n):
            sum1 = np.dot(A[i, :i], x[:i])
            sum2 = np.dot(A[i, i+1:], x[i+1:])
            x_new[i] = (b[i] - sum1 - sum2) / A[i, i]
        x = x_new.copy()
    return x

def gauss_seidel(A, b, x0, tol):
    n = len(A)
    x = x0.copy()
    iteration = 0
    while True:
        iteration += 1
        x_old = x.copy()
        for i in range(n):
            sum1 = np.dot(A[i, :i], x[:i])
            sum2 = np.dot(A[i, i+1:], x_old[i+1:])
            x[i] = (b[i] - sum1 - sum2) / A[i, i]
        if np.linalg.norm(x - x_old, ord=np.inf) < tol:
            break
    return x, iteration

def main():
    # Definir el sistema lineal
    A = np.array([
        [2, -1, 1],
        [2, 2, 2],
        [-1, -1, 2]
    ])
    b = np.array([-1, 4, -5])
    x0 = np.zeros(3)
    max_iterations = 25
    tol = 1e-5

    # a) Método de Jacobi
    jacobi_solution = jacobi(A, b, x0, max_iterations)
    print("a) Método de Jacobi después de 25 iteraciones:")
    print(jacobi_solution)
    print()

    # b) Método de Gauss-Seidel
    gauss_seidel_solution, gauss_seidel_iterations = gauss_seidel(A, b, x0, tol)
    print("b) Método de Gauss-Seidel con tolerancia 1e-5:")
    print(f"Solución: {gauss_seidel_solution}")
    print(f"Iteraciones: {gauss_seidel_iterations}")

if __name__ == "__main__":
    main()


a) Método de Jacobi después de 25 iteraciones:
[-20.82787284   2.         -22.82787284]

b) Método de Gauss-Seidel con tolerancia 1e-5:
Solución: [ 1.00000226  1.9999975  -1.00000012]
Iteraciones: 23


### **Ejercicio 6.**
6. El sistema lineal

   > $(x_1 - x_3 = 0.2)$ <br> $(-\frac{1}{2}x_1 + x_2 - \frac{1}{4} x_3 = -1.425)$ <br> $(x_1 -\frac{1}{2}x_2 + x_3 = 2)$

  tiene la solución $(0.9, -0.8, 0.7)$.

- **a)** ¿La matriz de coeficientes tiene diagonal estrictamente dominante?
> $
  A = \begin{bmatrix}
  1 & 0 & -1 \\
  -\frac{1}{2} & 1 & -\frac{1}{4}\\
  1 & -\frac{1}{2} & 1
  \end{bmatrix}
  $

- **b)** Utilice el método iterativo de Gauss-Seidel para aproximar la solución para el sistema lineal con una tolerancia de $10^{-22}$ y un máximo de 300 iteraciones.

- **c)** ¿Qué pasa en la parte b) cuando el sistema cambia por el siguiente?

   > $(x_1 - 2x_3 = 0.2)$ <br> $(-\frac{1}{2}x_1 + x_2 - \frac{1}{4} x_3 = -1.425)$ <br> $(x_1 -\frac{1}{2}x_2 + x_3 = 2)$

In [50]:
import numpy as np

def gauss_seidel(A, b, x0, tol, max_iterations):
    n = len(A)
    x = x0.copy()
    for iteration in range(max_iterations):
        x_old = x.copy()
        for i in range(n):
            sum1 = np.dot(A[i, :i], x[:i])
            sum2 = np.dot(A[i, i+1:], x_old[i+1:])
            x[i] = (b[i] - sum1 - sum2) / A[i, i]
        if np.linalg.norm(x - x_old, ord=np.inf) < tol:
            break
    return x, iteration

def is_diagonally_dominant(A):
    n = A.shape[0]
    for i in range(n):
        row_sum = sum(abs(A[i, j]) for j in range(n) if j != i)
        if abs(A[i, i]) <= row_sum:
            return False
    return True

def main():
    # Parte a: Verificar diagonal dominante
    A = np.array([
        [1, 0, -1],
        [-0.5, 1, -0.25],
        [1, -0.5, 1]
    ])
    is_dominant = is_diagonally_dominant(A)
    print("a) La matriz es diagonalmente dominante:", is_dominant)

    # Parte b: Método de Gauss-Seidel para el sistema original
    b = np.array([0.2, -1.425, 2])
    x0 = np.zeros(3)
    tol = 1e-22
    max_iterations = 300

    solution, iterations = gauss_seidel(A, b, x0, tol, max_iterations)
    print("\nb) Método de Gauss-Seidel para el sistema original")
    print("Solución aproximada:", solution)
    print("Número de iteraciones:", iterations)

    # Parte c: Método de Gauss-Seidel para el sistema modificado
    A_modified = np.array([
        [1, 0, -2],
        [-0.5, 1, -0.25],
        [1, -0.5, 1]
    ])
    solution_modified, iterations_modified = gauss_seidel(A_modified, b, x0, tol, max_iterations)
    print("\nc) Método de Gauss-Seidel para el sistema modificado")
    print("Solución aproximada:", solution_modified)
    print("Número de iteraciones:", iterations_modified)

if __name__ == "__main__":
    main()


a) La matriz es diagonalmente dominante: False

b) Método de Gauss-Seidel para el sistema original
Solución aproximada: [ 0.9 -0.8  0.7]
Número de iteraciones: 299

c) Método de Gauss-Seidel para el sistema modificado
Solución aproximada: [ 2.15687283e+41  1.34804552e+41 -1.48285007e+41]
Número de iteraciones: 299


### **Ejercicio 7.**
Repita el ejercicio 11 usando el método de Jacobi.

In [51]:
import numpy as np

def jacobi(A, b, x0, tol, max_iterations):
    n = len(A)
    x = x0.copy()
    x_new = np.zeros_like(x0)
    for iteration in range(max_iterations):
        for i in range(n):
            sum1 = np.dot(A[i, :i], x[:i])
            sum2 = np.dot(A[i, i+1:], x[i+1:])
            x_new[i] = (b[i] - sum1 - sum2) / A[i, i]
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            break
        x = x_new.copy()
    return x, iteration

def is_diagonally_dominant(A):
    n = A.shape[0]
    for i in range(n):
        row_sum = sum(abs(A[i, j]) for j in range(n) if j != i)
        if abs(A[i, i]) <= row_sum:
            return False
    return True

def main():
    # Parte a: Verificar diagonal dominante
    A = np.array([
        [1, 0, -1],
        [-0.5, 1, -0.25],
        [1, -0.5, 1]
    ])
    is_dominant = is_diagonally_dominant(A)
    print("a) La matriz es diagonalmente dominante:", is_dominant)

    # Parte b: Método de Jacobi para el sistema original
    b = np.array([0.2, -1.425, 2])
    x0 = np.zeros(3)
    tol = 1e-22
    max_iterations = 300

    solution, iterations = jacobi(A, b, x0, tol, max_iterations)
    print("\nb) Método de Jacobi para el sistema original")
    print("Solución aproximada:", solution)
    print("Número de iteraciones:", iterations)

    # Parte c: Método de Jacobi para el sistema modificado
    A_modified = np.array([
        [1, 0, -2],
        [-0.5, 1, -0.25],
        [1, -0.5, 1]
    ])
    solution_modified, iterations_modified = jacobi(A_modified, b, x0, tol, max_iterations)
    print("\nc) Método de Jacobi para el sistema modificado")
    print("Solución aproximada:", solution_modified)
    print("Número de iteraciones:", iterations_modified)

if __name__ == "__main__":
    main()


a) La matriz es diagonalmente dominante: False

b) Método de Jacobi para el sistema original
Solución aproximada: [ 0.90025541 -0.80004033  0.70012933]
Número de iteraciones: 299

c) Método de Jacobi para el sistema modificado
Solución aproximada: [ 1.34478913e+43 -7.28028158e+42  1.56650340e+43]
Número de iteraciones: 299


### **Ejercicio 8.**
8. Un cable coaxial está formado por un conductor interno de 0.1 pulgadas cuadradas y un conductor externo de 0.5 pulgadas cuadradas. El potencial en un punto en la sección transversal del cable se describe mediante la ecuación de Laplace. Suponga que el conductor interno se mantiene en 0 volts y el conductor externo se mantiene en 110 volts. Aproximar el potencial entre los dos conductores requiere resolver el siguiente sistema lineal.

$
A = \begin{bmatrix}
4 & -1 & 0 & 0 & -1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
-1 & 4 & -1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & -1 & 4 & -1 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & -1 & 4 & 0 & -1 & 0 & 0 & 0 & 0 & 0 & 0 \\
-1 & 0 & 0 & 0 & 4 & 0 & -1 & 0 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & -1 & 0 & 4 & 0 & -1 & 0 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & -1 & 0 & 4 & 0 & -1 & 0 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & -1 & 0 & 4 & 0 & 0 & 0 & -1 \\
0 & 0 & 0 & 0 & 0 & 0 & -1 & 0 & 4 & -1 & 0 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & -1 & 4 & -1 & 0 \\
0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & 0 & -1 & 4 & -1 \\
0 & 0 & 0 & 0 & 0 & -1 & 0 & 0 & 0 & 0 & -1 & 4
\end{bmatrix}\quad\begin{bmatrix}
W_1 \\
W_2 \\
W_3 \\
W_4 \\
W_5 \\
W_6 \\
W_7 \\
W_8 \\
W_9 \\
W_{10} \\
W_{11} \\
W_{12}
\end{bmatrix}
\quad  = \begin{bmatrix}
220 \\
110 \\
110 \\
220 \\
110 \\
110 \\
110 \\
110 \\
220 \\
110 \\
110 \\
220
\end{bmatrix}
$

- **a)** ¿La matriz es estrictamente diagonalmente dominante?

- **b)** Resuelva el sistema lineal usando el método de Jacobi con $\mathbf{x}^{(0)} = 0$ y $\text{TOL} = 10^{-2}$.

- **c)** Repita la parte b) mediante el método de Gauss-Seidel.

In [52]:
import numpy as np

def jacobi(A, b, x0, tol, max_iterations):
    n = len(A)
    x = x0.copy()
    x_new = np.zeros_like(x0)
    for iteration in range(max_iterations):
        for i in range(n):
            sum1 = np.dot(A[i, :i], x[:i])
            sum2 = np.dot(A[i, i+1:], x[i+1:])
            x_new[i] = (b[i] - sum1 - sum2) / A[i, i]
        if np.linalg.norm(x_new - x, ord=np.inf) < tol:
            return x_new, iteration + 1
        x = x_new.copy()
    return x, max_iterations

def gauss_seidel(A, b, x0, tol, max_iterations):
    n = len(A)
    x = x0.copy()
    for iteration in range(max_iterations):
        x_old = x.copy()
        for i in range(n):
            sum1 = np.dot(A[i, :i], x[:i])
            sum2 = np.dot(A[i, i+1:], x_old[i+1:])
            x[i] = (b[i] - sum1 - sum2) / A[i, i]
        if np.linalg.norm(x - x_old, ord=np.inf) < tol:
            return x, iteration + 1
    return x, max_iterations

def is_diagonally_dominant(A):
    n = A.shape[0]
    for i in range(n):
        row_sum = sum(abs(A[i, j]) for j in range(n) if j != i)
        if abs(A[i, i]) <= row_sum:
            return False
    return True

def main():
    A = np.array([
        [4, -1, 0, 0, -1, 0, 0, 0, 0, 0, 0, 0],
        [-1, 4, -1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, -1, 4, -1, 0, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, -1, 4, 0, -1, 0, 0, 0, 0, 0, 0],
        [-1, 0, 0, 0, 4, 0, -1, 0, 0, 0, 0, 0],
        [0, 0, 0, -1, 0, 4, 0, -1, 0, 0, 0, 0],
        [0, 0, 0, 0, -1, 0, 4, 0, -1, 0, 0, 0],
        [0, 0, 0, 0, 0, -1, 0, 4, 0, 0, 0, -1],
        [0, 0, 0, 0, 0, 0, -1, 0, 4, -1, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, -1, 4, -1, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, -1, 4, -1],
        [0, 0, 0, 0, 0, -1, 0, 0, 0, 0, -1, 4]
    ])

    b = np.array([220, 110, 110, 220, 110, 110, 110, 110, 220, 110, 110, 220])
    x0 = np.zeros(12)
    tol = 1e-2
    max_iterations = 300

    # Parte a: Verificar diagonal dominante
    is_dominant = is_diagonally_dominant(A)
    print("a) La matriz es diagonalmente dominante:", is_dominant)

    # Parte b: Método de Jacobi para el sistema
    solution_jacobi, iterations_jacobi = jacobi(A, b, x0, tol, max_iterations)
    print("\nb) Método de Jacobi")
    print("Solución aproximada:", solution_jacobi)
    print("Número de iteraciones:", iterations_jacobi)

    # Parte c: Método de Gauss-Seidel para el sistema
    solution_gauss_seidel, iterations_gauss_seidel = gauss_seidel(A, b, x0, tol, max_iterations)
    print("\nc) Método de Gauss-Seidel")
    print("Solución aproximada:", solution_gauss_seidel)
    print("Número de iteraciones:", iterations_gauss_seidel)

if __name__ == "__main__":
    main()


a) La matriz es diagonalmente dominante: True

b) Método de Jacobi
Solución aproximada: [87.9910484  65.99104807 65.99104807 87.9910484  65.99104807 65.99104807
 65.99104807 65.99104807 87.9910484  65.99104807 65.99104807 87.9910484 ]
Número de iteraciones: 13

c) Método de Gauss-Seidel
Solución aproximada: [87.99858534 65.99922212 65.99954152 87.9997184  65.99922212 65.99982312
 65.99954152 65.99988742 87.9997184  65.99982312 65.99988742 87.99992764]
Número de iteraciones: 10
