<a href="https://colab.research.google.com/github/Andro2k/Metodos-Numericos/blob/main/Tarea_10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# <a href="https://colab.research.google.com/drive/1omS5e4xV-hPSS7hZ1h1XhzhWRdJO4ooQ?usp=sharing">**Tarea 10**</a>
* **Estudiante:** Jose Luis Andino
* **Materia:** Metodos Numericos
* **Carrera:** Computación
* **Docente:** Jonathan A. Zea



## **CONJUNTO DE EJERCICIOS**



### **Ejercicio 1.**
Realice las siguientes multiplicaciones matriz-matriz:

**A)**
   > \begin{bmatrix}
   2 & -3 \\
   3 & -1
   \end{bmatrix}
   > \begin{bmatrix}
   1 & 5 \\
   2 & 0
   \end{bmatrix}

**B)**
   > \begin{bmatrix}
   2 & -3 \\
   3 & -1
   \end{bmatrix}
   > \begin{bmatrix}
   1 & 5 & -4 \\
   -3 & 2 & 0
   \end{bmatrix}

**C)**
   > \begin{bmatrix}
   2 & -3 & 1 \\
   4 & 3 & 0 \\
   5 & 2 & -4
   \end{bmatrix}
   > \begin{bmatrix}
   0 & 1 & -2 \\
   1 & 0 & -1 \\
   2 & 3 & -2
   \end{bmatrix}


**D)**
   > \begin{bmatrix}
   2 & 1 & 2 \\
   -2 & 3 & 0 \\
   2 & -1 & 3
   \end{bmatrix}
   > \begin{bmatrix}
   1 & -2 \\
   -4 & 1 \\
   0 & 2
   \end{bmatrix}



In [16]:
import numpy as np

def multiplicar_matrices(A, B):
    if A.shape[1] != B.shape[0]:
        raise ValueError("Las dimensiones de las matrices no son válidas para la multiplicación.")
    return np.dot(A, B)

# Matrices del ejercicio 1
A1 = np.array([
    [2, -3],
    [3, -1]
])

B1 = np.array([
    [1, 5],
    [2, 0]
])

A2 = np.array([
    [2, -3],
    [3, -1]
])

B2 = np.array([
    [1, 5, -4],
    [-3, 2, 0]
])

A3 = np.array([
    [2, -3, 1],
    [4, 3, 0],
    [5, 2, -4]
])

B3 = np.array([
    [0, 1, -2],
    [1, 0, -1],
    [2, 3, -2]
])

A4 = np.array([
    [2, 1, 2],
    [-2, 3, 0],
    [2, -1, 3]
])

B4 = np.array([
    [1, -2],
    [-4, 1],
    [0, 2]
])

# Realizar las multiplicaciones
resultado1 = multiplicar_matrices(A1, B1)
resultado2 = multiplicar_matrices(A2, B2)
resultado3 = multiplicar_matrices(A3, B3)
resultado4 = multiplicar_matrices(A4, B4)

# Mostrar resultados
print("El resultado de la multiplicación de las matrices a es:")
print(resultado1)
print("\nEl resultado de la multiplicación de las matrices b es:")
print(resultado2)
print("\nEl resultado de la multiplicación de las matrices c es:")
print(resultado3)
print("\nEl resultado de la multiplicación de las matrices d es:")
print(resultado4)


El resultado de la multiplicación de las matrices a es:
[[-4 10]
 [ 1 15]]

El resultado de la multiplicación de las matrices b es:
[[ 11   4  -8]
 [  6  13 -12]]

El resultado de la multiplicación de las matrices c es:
[[ -1   5  -3]
 [  3   4 -11]
 [ -6  -7  -4]]

El resultado de la multiplicación de las matrices d es:
[[ -2   1]
 [-14   7]
 [  6   1]]


### **Ejercicio 2.**
Determine cuáles de las siguientes matrices son no singulares y calcule la inversa de esas matrices:

**A)**
> \begin{bmatrix}
4 & 2 & 6 \\
3 & 0 & 7 \\
-2 & -1 & -3
\end{bmatrix}

**B)**
> \begin{bmatrix}
1&2&0\\
2&1&-1\\
3&1&1
\end{bmatrix}

**C)**
> \begin{bmatrix}
1&1&-1&1\\
1&2&-4&-2\\
2&1&1&5\\
-1&0&-2&-4
\end{bmatrix}


**D)**
> \begin{bmatrix}
4&0&0&0\\
6&7&0&0\\
9&11&1&0\\
5&4&1&1
\end{bmatrix}

In [17]:
import numpy as np

def es_no_singular(matriz):
    det = np.linalg.det(matriz)
    return det != 0

def inversa_matriz(matriz):

    if es_no_singular(matriz):
        return np.linalg.inv(matriz)
    else:
        return None

# Matrices del ejercicio 2
A = np.array([
    [4, 2, 6],
    [3, 0, 7],
    [-2, -1, -3]
])

B = np.array([
    [1, 2, 0],
    [2, 1, -1],
    [3, 1, 1]
])

C = np.array([
    [1, 1, -1, 1],
    [1, 2, -4, -2],
    [2, 1, 1, 5],
    [-1, 0, -2, -4]
])

D = np.array([
    [4, 0, 0, 0],
    [6, 7, 0, 0],
    [9, 11, 1, 0],
    [5, 4, 1, 1]
])

# Lista de matrices
matrices = [A, B, C, D]

# Verificar cuáles matrices son no singulares y calcular sus inversas
for i, matriz in enumerate(matrices):
    print(f"Matriz {chr(65 + i)}:")
    print(matriz)
    if es_no_singular(matriz):
        print("La matriz es no singular.")
        inversa = inversa_matriz(matriz)
        print("Inversa de la matriz:")
        print(inversa)
    else:
        print("La matriz es singular y no tiene inversa.")
    print()


Matriz A:
[[ 4  2  6]
 [ 3  0  7]
 [-2 -1 -3]]
La matriz es singular y no tiene inversa.

Matriz B:
[[ 1  2  0]
 [ 2  1 -1]
 [ 3  1  1]]
La matriz es no singular.
Inversa de la matriz:
[[-0.25   0.25   0.25 ]
 [ 0.625 -0.125 -0.125]
 [ 0.125 -0.625  0.375]]

Matriz C:
[[ 1  1 -1  1]
 [ 1  2 -4 -2]
 [ 2  1  1  5]
 [-1  0 -2 -4]]
La matriz es singular y no tiene inversa.

Matriz D:
[[ 4  0  0  0]
 [ 6  7  0  0]
 [ 9 11  1  0]
 [ 5  4  1  1]]
La matriz es no singular.
Inversa de la matriz:
[[ 0.25        0.          0.          0.        ]
 [-0.21428571  0.14285714 -0.         -0.        ]
 [ 0.10714286 -1.57142857  1.         -0.        ]
 [-0.5         1.         -1.          1.        ]]



### **Ejercicio 3.**
Resuelva los sistemas lineales 4 x 4 que tienen la misma matriz de coeficientes:
> \begin{cases}
x_1 - x_2 + 2x_3 - x_4 = 6\\
x_1 - x_3 + x_4 = 4\\
2x_1 + x_2 + 3x_3 - 4x_4 = -2\\
- x_2 + x_3 - x_4 = 5
\end{cases}

> \begin{cases}
x_1 - x_2 + 2x_3 - x_4 = 1\\
x_1 - x_3 + x_4 = 1\\
2x_1 + x_2 + 3x_3 - 4x_4 = 2\\
- x_2 + x_3 - x_4 = -1
\end{cases}

In [18]:
import numpy as np

# Definir la matriz de coeficientes
A = np.array([
    [1, -1, 2, -1],
    [1, 0, -1, 1],
    [2, 1, 3, -4],
    [0, -1, 1, -1]
])

# Definir los vectores de términos independientes
b1 = np.array([6, 4, -2, 5])
b2 = np.array([1, 1, 2, -1])

# Resolver los sistemas lineales
x1 = np.linalg.solve(A, b1)
x2 = np.linalg.solve(A, b2)

# Mostrar los resultados
print("Solución del primer sistema:")
print(x1)
print("\nSolución del segundo sistema:")
print(x2)


Solución del primer sistema:
[ 3. -6. -2. -1.]

Solución del segundo sistema:
[1. 1. 1. 1.]


### **Ejercicio 4.**
Encuentre los valores de $( A )$ que hacen que la siguiente matriz sea singular:

> $A=$\begin{bmatrix}
      1 & -1 & \alpha \\
      2 & 2 & 1 \\
      0 & \alpha & -{3}/{2}
      \end{bmatrix}

In [19]:
import numpy as np
from sympy import symbols, solve, Matrix

# Definir el símbolo alfa
alpha = symbols('alpha')

# Definir la matriz
A = Matrix([
    [1, -1, alpha],
    [2, 2, 1],
    [0, alpha, -3/2]
])

# Calcular el determinante de la matriz
det_A = A.det()

# Encontrar los valores de alfa que hacen que el determinante sea cero
valores_alpha = solve(det_A, alpha)

# Mostrar los resultados
print("Valores de alfa que hacen que la matriz sea singular:")
print(valores_alpha)


Valores de alfa que hacen que la matriz sea singular:
[-1.50000000000000, 2.00000000000000]


### **Ejercicio 5.**
Resuelva los siguientes sistemas lineales:


**A.**
>\begin{cases}
\begin{bmatrix}
1 & 0 & 0 \\
2 & 1 & 0 \\
-1 & 0 & 1 \\
\end{bmatrix}
\begin{bmatrix}
2 & 3 &-1 \\
0 &-2 & 1 \\
0 & 0 & 3
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix}
=
\begin{bmatrix}
2 \\
-1 \\
1
\end{bmatrix}
\end{cases}

**B.**
>\begin{cases}
\begin{bmatrix}
2 & 0 & 0 \\
-1 & 1 & 0 \\
3 & 2 & -1 \\
\end{bmatrix}
\begin{bmatrix}
1 & 1 & 1 \\
0 & 1 & 2\\
0 & 0 & 1
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
x_3
\end{bmatrix}
=
\begin{bmatrix}
-1 \\
3 \\
0
\end{bmatrix}
\end{cases}

In [20]:
import numpy as np

# Definir las matrices para el sistema A
A1 = np.array([
    [1, 0, 0],
    [2, 1, 0],
    [-1, 0, 1]
])

A2 = np.array([
    [2, 3, -1],
    [0, -2, 1],
    [0, 0, 3]
])

# Multiplicar las matrices A1 y A2
A = np.dot(A1, A2)

# Definir el vector de constantes para el sistema A
b = np.array([2, -1, 1])

# Resolver el sistema A
x_A = np.linalg.solve(A, b)

print("Solución del sistema A:")
print(x_A)

# Definir las matrices para el sistema B
B1 = np.array([
    [2, 0, 0],
    [-1, 1, 0],
    [3, 2, -1]
])

B2 = np.array([
    [1, 1, 1],
    [0, 1, 2],
    [0, 0, 1]
])

# Multiplicar las matrices B1 y B2
B = np.dot(B1, B2)

# Definir el vector de constantes para el sistema B
b_B = np.array([-1, 3, 0])

# Resolver el sistema B
x_B = np.linalg.solve(B, b_B)

print("Solución del sistema B:")
print(x_B)


Solución del sistema A:
[-3.  3.  1.]
Solución del sistema B:
[ 0.5 -4.5  3.5]


### **Ejercicio 6.**
Factorice las siguientes matrices en la descomposición $LU$ mediante el algoritmo de factorización $LU$ con $l_{ii} = 1 $ para todas las $i$:

**A.**
> \begin{bmatrix}
  2 & -1 & 1 \\
  3 & 3 & 9 \\
  3 & 3 & 5
  \end{bmatrix}

**B.**
> \begin{bmatrix}
  1.012 & -2.132 & 3.104 \\
  -2.132 & 4.096 & -7.013 \\
  3.104 & -7.013 & 0.014
  \end{bmatrix}

**C.**
> \begin{bmatrix}
  2 & 0 & 0 & 0 \\
  1 & 1.5 & 0 & 0 \\
  0 & -3 & 0.5 & 0 \\
  2 & -2 & 1 & 1
  \end{bmatrix}

**D.**
> \begin{bmatrix}
  2.1756 & 4.0231 & -2.1732 & 5.1967 \\
  -4.0231 & 6.0000 & 0 & 1.1973 \\
  -1.0000 & -5.2107 & 1.1111 & 0 \\
  6.0235 & 7.0000 & 0 & -4.1561
  \end{bmatrix}


In [21]:
import numpy as np
from scipy.linalg import lu

# Definir las matrices
matrices = {
    'A': np.array([
        [2, -1, 1],
        [3, 3, 9],
        [3, 3, 5]
    ]),
    'B': np.array([
        [1.012, -2.132, 3.104],
        [-2.132, 4.096, -7.013],
        [3.104, -7.013, 0.014]
    ]),
    'C': np.array([
        [2, 0, 0, 0],
        [1, 1.5, 0, 0],
        [0, -3, 0.5, 0],
        [2, -2, 1, 1]
    ]),
    'D': np.array([
        [2.1756, 4.0231, -2.1732, 5.1967],
        [-4.0231, 6.0000, 0, 1.1973],
        [-1.0000, -5.2107, 1.1111, 0],
        [6.0235, 7.0000, 0, -4.1561]
    ])
}

# Realizar la factorización LU para cada matriz
for key, matrix in matrices.items():
    P, L, U = lu(matrix)
    print(f"Factorización LU de la matriz {key}:")
    print("L:")
    print(L)
    print("U:")
    print(U)
    print("P:")
    print(P)
    print("\n")


Factorización LU de la matriz A:
L:
[[ 1.          0.          0.        ]
 [ 0.66666667  1.          0.        ]
 [ 1.         -0.          1.        ]]
U:
[[ 3.  3.  9.]
 [ 0. -3. -5.]
 [ 0.  0. -4.]]
P:
[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


Factorización LU de la matriz B:
L:
[[ 1.          0.          0.        ]
 [-0.68685567  1.          0.        ]
 [ 0.32603093 -0.21424728  1.        ]]
U:
[[ 3.104      -7.013       0.014     ]
 [ 0.         -0.72091881 -7.00338402]
 [ 0.          0.          1.59897957]]
P:
[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]


Factorización LU de la matriz C:
L:
[[ 1.          0.          0.          0.        ]
 [ 0.          1.          0.          0.        ]
 [ 1.          0.66666667  1.          0.        ]
 [ 0.5        -0.5         0.375       1.        ]]
U:
[[ 2.          0.          0.          0.        ]
 [ 0.         -3.          0.5         0.        ]
 [ 0.          0.          0.66666667  1.        ]
 [ 0.          0.          0.         -0.

### **Ejercicio 7.**
Modifique el algoritmo de eliminación gaussiana de tal forma que se pueda utilizar para resolver un sistema lineal usando la descomposición $LU$ y, a continuación, resuelva los siguientes sistemas lineales:

**A.**
> \begin{cases}
  2x_1 - x_2 + x_3 = -1 \\
  3x_1 + 3x_2 + 9x_3 = 0 \\
  3x_1 + 3x_2 + 5x_3 = 4
  \end{cases}


**B.**
> \begin{cases}
  1.012x_1 - 2.132x_2 + 3.104x_3 = 1.984 \\
  -2.132x_1 + 4.096x_2 - 7.013x_3 = -5.049 \\
  3.104x_1 - 7.013x_2 + 0.014x_3 = -3.895
  \end{cases}

**C.**
> \begin{cases}
  2x_1 = 3 \\
  x_1 + 1.5x_2 = 4.5 \\
  -3x_2 + 0.5x_3 = -6.6 \\
  2x_1 - 2x_2 + x_3 + x_4 = 0.8
  \end{cases}


**D.**
> \begin{cases}
  2.1756x_1 + 4.0231x_2 - 2.1732x_3 + 5.1967x_4 = 17.102 \\
  -4.0231x_1 + 6.0000x_2 = -6.1593 \\
  -1.0000x_1 - 5.2107x_2 + 1.1111x_3 = 3.0004 \\
  6.0235x_1 + 7.0000x_2 - 4.1561x_4 = 0.0000
  \end{cases}

In [22]:
import numpy as np
from scipy.linalg import lu

# Definir una función para resolver Ax = b usando la descomposición LU
def solve_lu(A, b):
    P, L, U = lu(A)
    # Resolver Ly = Pb para y
    y = np.linalg.solve(L, np.dot(P, b))
    # Resolver Ux = y para x
    x = np.linalg.solve(U, y)
    return x

# Definir las matrices y vectores para cada sistema
systems = {
    'A': (np.array([
        [2, -1, 1],
        [3, 3, 9],
        [3, 3, 5]
    ]), np.array([-1, 0, 4])),
    'B': (np.array([
        [1.012, -2.132, 3.104],
        [-2.132, 4.096, -7.013],
        [3.104, -7.013, 0.014]
    ]), np.array([1.984, -5.049, -3.895])),
    'C': (np.array([
        [2, 0, 0, 0],
        [1, 1.5, 0, 0],
        [0, -3, 0.5, 0],
        [2, -2, 1, 1]
    ]), np.array([3, 4.5, -6.6, 0.8])),
    'D': (np.array([
        [2.1756, 4.0231, -2.1732, 5.1967],
        [-4.0231, 6.0000, 0, 1.1973],
        [-1.0000, -5.2107, 1.1111, 0],
        [6.0235, 7.0000, 0, -4.1561]
    ]), np.array([17.102, -6.1593, 3.0004, 0]))
}

# Resolver cada sistema y mostrar las soluciones
for key, (A, b) in systems.items():
    x = solve_lu(A, b)
    print(f"Solución del sistema {key}:")
    print(x)
    print("\n")


Solución del sistema A:
[ 1.  2. -1.]


Solución del sistema B:
[1. 1. 1.]


Solución del sistema C:
[  1.5  -5.4 -30.8  21.5]


Solución del sistema D:
[ 4.5834584   0.64756529 22.5539797   7.01162597]


